version: '3.3'
services:
    www:
        networks:
          - nginx-proxy
        env_file: .env
        ports:
            - '8080:8080'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        restart: always
        logging:
            options:
                max-size: 10m
        build: .
        command: "http-server /src/build"
networks:
  nginx-proxy:
    external: true
